M1, M2, N1, N2, P1, P2, Q1, Q2 = map(int, input("Nhập lần lượt tọa độ của các điểm M, N, P, Q: ").split())
MN = ((M1 + N1)/2, (N2 + M2)/2)
NP = ((N1 + P1)/2, (N2 + P2)/2)
PQ = ((P1 + Q1)/2, (P2 + Q2)/2)
QM = ((Q1 + M1)/2, (Q2 + M2)/2)
print("Trung điểm của cạnh MN là: ", MN)
print("Trung điểm của cạnh NP là: ", NP)
print("Trung điểm của cạnh PQ là: ", PQ)
print("Trung điểm của cạnh QM là: ", QM)
